package ch.client.file;

import com.trm.webservice.client.file.model.FileEntity;
import com.trm.webservice.client.file.model.IOException_Exception;
import com.trm.webservice.client.file.model.ObjectFactory;
import com.trm.webservice.client.file.model.UploadResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-08T17:16:01.254+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://server.webservice.trm.com/", name = "UploadFileWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface UploadFileWebService {

    @WebMethod
    @RequestWrapper(localName = "uploadFileInnovate", targetNamespace = "http://server.webservice.trm.com/", className = "com.trm.webservice.client.file.model.UploadFileInnovate")
    @ResponseWrapper(localName = "uploadFileInnovateResponse", targetNamespace = "http://server.webservice.trm.com/", className = "com.trm.webservice.client.file.model.UploadFileInnovateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.trm.webservice.client.file.model.UploadResponse> uploadFileInnovate(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<com.trm.webservice.client.file.model.FileEntity> arg0
    ) throws IOException_Exception;

    @WebMethod
    @RequestWrapper(localName = "uploadFileUeditor", targetNamespace = "http://server.webservice.trm.com/", className = "com.trm.webservice.client.file.model.UploadFileUeditor")
    @ResponseWrapper(localName = "uploadFileUeditorResponse", targetNamespace = "http://server.webservice.trm.com/", className = "com.trm.webservice.client.file.model.UploadFileUeditorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.trm.webservice.client.file.model.UploadResponse> uploadFileUeditor(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<com.trm.webservice.client.file.model.FileEntity> arg0
    ) throws IOException_Exception;
}
