package ch.client.file;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-08T17:16:01.258+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "UploadFileWebServiceImplService", 
                  wsdlLocation = "http://localhost:8084/trm-common-service-oss/tradingWS/uploadFile?wsdl",
                  targetNamespace = "http://impl.server.webservice.trm.com/") 
public class UploadFileWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.server.webservice.trm.com/", "UploadFileWebServiceImplService");
    public final static QName UploadFileWebServiceImplPort = new QName("http://impl.server.webservice.trm.com/", "UploadFileWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8084/trm-common-service-oss/tradingWS/uploadFile?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UploadFileWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8084/trm-common-service-oss/tradingWS/uploadFile?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UploadFileWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UploadFileWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UploadFileWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UploadFileWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UploadFileWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UploadFileWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UploadFileWebService
     */
    @WebEndpoint(name = "UploadFileWebServiceImplPort")
    public UploadFileWebService getUploadFileWebServiceImplPort() {
        return super.getPort(UploadFileWebServiceImplPort, UploadFileWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UploadFileWebService
     */
    @WebEndpoint(name = "UploadFileWebServiceImplPort")
    public UploadFileWebService getUploadFileWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UploadFileWebServiceImplPort, UploadFileWebService.class, features);
    }

}
