
package ch.client.file.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-08T17:16:01.250+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "IOException", targetNamespace = "http://server.webservice.trm.com/")
public class IOException_Exception extends Exception {
    
    private com.trm.webservice.client.file.model.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, com.trm.webservice.client.file.model.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, com.trm.webservice.client.file.model.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public com.trm.webservice.client.file.model.IOException getFaultInfo() {
        return this.ioException;
    }
}
